version: '3.8'

services:
  app:
    container_name: app
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_DB=knowledge_keeper_db
      - POSTGRES_USER=knowledge_keeper_user
      - POSTGRES_PASSWORD=knowledge_keeper_password
    ports:
      - 5432:5432
    volumes:
      - ./.db_data/postgres/:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    restart: always
      


