{
 "title": "Request",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "app_http_request{quantile=\"0.5\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expr": "app_http_request_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Up status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}